---
title: "SQL"
output: html_document
date: "2023-08-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RMySQL)
library(tidyverse)
library(rvest)
library(magrittr)
library(ggmap)
library(stringr)
library(RColorBrewer)
library(dplyr)
library(ggplot2)
library(flextable)
```

```{r}
lapply(dbListConnections(MySQL()), dbDisconnect)
mysqlconnection <-  dbConnect(RMySQL::MySQL(),
                            dbname='microbiome',
                            host='172.20.192.231',
                            port=3306,
                            user='darias',
                            password='Password123#@!')
```

```{r}
dbListTables(mysqlconnection)
```

```{r}
result1 <- dbSendQuery(mysqlconnection, "select type, host_id from site join host on site.site_id = host.site_id") 
site <- fetch(result1, n =-1)
site
site_type <- data.frame(table(site$type)) %>%
  rename(Number = Freq, Site = Var1)

piepercent <- site_type$Number * 100 / sum (site_type$Number)

ggplot(data = site_type, aes(x = "", y = piepercent, fill = Site)) +
  geom_bar(stat="identity", width = 1) +
  coord_polar("y", start = 0) +
  theme_void() +
  scale_fill_brewer(palette = "Set3")
```


```{r}
result2 <- dbSendQuery(mysqlconnection, "select geographic_location, host_id from host") 
country <- fetch(result2)
country <- data.frame(country) 
country <- country %>% 
  separate_rows(geographic_location, sep = ",")

lat_longs <- country %>%
  geocode(geographic_location, method = 'osm', lat = latitude , long = longitude)
lat_longs <- data.frame(lat_longs)
```

```{r}
library(maps)

ggplot(lat_longs) +
  geom_map(dat=world_map, map = world_map, aes(map_id=region), 
                    fill="white", color="black") +
  geom_map(map = world_map, aes(map_id = geographic_location), 
                    fill = "steelblue", colour = "black") +
  expand_limits(x = world_map$long, y = world_map$lat) + 
  theme(legend.position="none") +
  labs(y = "", x = "")
```

```{r}
result3 <- dbSendQuery(mysqlconnection, "select method_type, study_id from study join method on method.method_id = study.method_id") 
method <-fetch(result3, n =-1)
method
data.frame(table(method$method_type)) %>%
  rename(Number = Freq, Name = Var1)

```

```{r}
result4 <- dbSendQuery(mysqlconnection, "select year, journal, doi from publication") 
publication <-fetch(result4, n =-1)
publication
year <- data.frame(table(publication$year)) %>%
  rename(Number = Freq, Year= Var1)
ggplot(data=year, aes(x=Year, y=Number)) +
  geom_bar(stat="identity", fill="steelblue")+
  theme_minimal() +
  labs(y= "number of articles", x = "year")
```
```{r}
result5 <- dbSendQuery(mysqlconnection, "select name as disease, complication_or_side_disease as side_disease, genus, dysbiosis from microbe join study on study.microbe_id = microbe.microbe_id join host on study.host_id = host.host_id join `condition` on host.condition_id = condition.condition_id where genus <> 'NA' AND dysbiosis = 'Missing' AND (name = 'Type 2 diabetes' OR name = 'Diabetic retinopathy')") 
microbe <- fetch(result5, n =-1)
microbe

```
```{r}
result6 <- dbSendQuery(mysqlconnection, "select distinct dysbiosis, phylum, control_group from microbe join study on study.microbe_id = microbe.microbe_id join host on study.host_id = host.host_id where genus <> 'NA' and dysbiosis = 'decreased' and control_group = 'Palaeofaeces'") 
microbe <- fetch(result6, n =-1)
microbe
```
```{r}
result7 <- dbSendQuery(mysqlconnection, "select distinct dysbiosis, phylum, control_group from microbe join study on study.microbe_id = microbe.microbe_id join host on study.host_id = host.host_id where genus <> 'NA' and dysbiosis = 'increased' and control_group = 'Non-industrial modern subjects'") 
microbe <- fetch(result7, n =-1)
microbeins
```

