INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (1,'1678','Actinomycetota','Actinomycetes','Bifidobacteriales','Bifidobacteriaceae','Bifidobacterium',NULL),
	 (2,'572511','Bacillota','Clostridia','Clostridiales','Lachnospiraceae','Blautia',NULL),
	 (3,'68337','Deferribacterota','Deferribacteres',NULL,NULL,NULL,NULL),
	 (4,'841','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Roseburia',NULL),
	 (5,'28050','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Lachnospira',NULL),
	 (6,'40544','Proteobacteria','Betaproteobacteria','Burkholderiales','Alcaligenaceae','Sutterella',NULL),
	 (7,'33042','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Coprococcus',NULL),
	 (8,'33024','Bacillota','Negativicutes','Acidaminococcales','Acidaminococcaceae','Phascolarctobacterium',NULL),
	 (9,'724','Pseudomonadota','Gammaproteobacteria','Pasteurellales','Pasteurellaceae','Haemophilus',NULL),
	 (10,'5052','Ascomycota','Eurotiomycetes','Eurotiales','Aspergillaceae','Aspergillus',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (11,'283','Pseudomonadota','Betaproteobacteria','Burkholderiales','Comamonadaceae','Comamonas',NULL),
	 (12,'207244','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Anaerostipes',NULL),
	 (13,'191303','Bacillota','Erysipelotrichia','Erysipelotrichales','Turicibacteraceae','Turicibacter',NULL),
	 (14,'216851','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Faecalibacterium',NULL),
	 (15,'52225','Bacillota','Negativicutes','Selenomonadales','Selenomonadaceae','Mitsuokella',NULL),
	 (16,'1301','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus',NULL),
	 (17,'1578','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Lactobacillus',NULL),
	 (18,'1485','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Clostridium',NULL),
	 (19,'551','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Erwiniaceae','Erwinia',NULL),
	 (20,'872','Thermodesulfobacteriota','Desulfovibrionia','Desulfovibrionales','Desulfovibrionaceae','Desulfovibrio',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (21,'118747','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae','Bulleidia',NULL),
	 (22,'830','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Butyrivibrio',NULL),
	 (23,'2152','Mycoplasmatota','Mollicutes','Anaeroplasmatales','Anaeroplasmataceae','Anaeroplasma',NULL),
	 (24,'82373','Bacillota','Negativicutes','Selenomonadales','Selenomonadaceae','Anaerovibrio',NULL),
	 (25,'32207','Actinomycetota','Actinomycetes','Micrococcales','Micrococcaceae','Rothia',NULL),
	 (26,'846','Pseudomonadota','Betaproteobacteria','Burkholderiales','Oxalobacteraceae','Oxalobacter ',NULL),
	 (27,'208596','Bacillota','Bacilli','Lactobacillales','Carnobacteriaceae','Carnobacterium sp. 17-4',NULL),
	 (28,'283168','Bacteroidota','Bacteroidia','Bacteroidales','Odoribacteraceae','Odoribacter',NULL),
	 (29,'119852','Bacillota','Clostridia','Eubacteriales','Ruminococcaceae','Oscillospira',NULL),
	 (30,'397864','Bacteroidota','Bacteroidia','Bacteroidales','Barnesiellaceae','Barnesiella',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (31,'1407607','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Fusicatenibacter',NULL),
	 (32,'1263','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Ruminococcus',NULL),
	 (33,'1501226','Bacillota','Clostridia','Eubacteriales','Peptostreptococcaceae','Romboutsia',NULL),
	 (34,'204475','Bacillota','Clostridia','Eubacteriales','Eubacteriales incertae sedis','Gemmiger',NULL),
	 (35,'816','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides',NULL),
	 (36,'44749','Bacillota','Clostridia','Eubacteriales','Ruminococcacea','Sporobacter','Sporobacter termitidis'),
	 (37,'328814','Bacteroidota','Bacteroidia','Bacteroidales','Rikenellaceae','Alistipes','Alistipes shahii'),
	 (38,'820','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides uniformis'),
	 (39,'47246','Bacillota','Clostridia','Eubacteriales','Ruminococcaceae','Ruminiclostridium','[Clostridium] viride'),
	 (40,'853','Bacillota','Clostridia','Eubacteriales','Ruminococcaceae','Faecalibacterium','Faecalibacterium prausnitzii');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (41,'871665','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Blautia','Blautia faecis'),
	 (42,'194','Campylobacterota','Epsilonproteobacteria','Campylobacterales','Campylobacteraceae','Campylobacter',NULL),
	 (43,'189330','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Dorea',NULL),
	 (44,'239759','Bacteroidota','Bacteroidia','Bacteroidales','Rikenellaceae','Alistipes',NULL),
	 (45,'375288','Bacteroidota','Bacteroidia','Bacteroidales','Tannerellaceae','Parabacteroides',NULL),
	 (46,'1912216','Actinomycetota','Actinomycetes','Propionibacteriales','Propionibacteriaceae','Cutibacterium',NULL),
	 (47,'3025755','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae','Erysipelatoclostridium',NULL),
	 (48,'135858','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae','Catenibacterium',NULL),
	 (49,'1283313','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Alloprevotella',NULL),
	 (50,'1016','Bacteroidota','Flavobacteriia','Flavobacteriales','Flavobacteriaceae','Capnocytophaga',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (51,'59732','Bacteroidota','Flavobacteriia','Flavobacteriales','Weeksellaceae','Chryseobacterium',NULL),
	 (52,'836','Bacteroidota','Bacteroidia','Bacteroidales','Porphyromonadaceae','Porphyromonas',NULL),
	 (53,'838','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Prevotella',NULL),
	 (54,'195950','Bacteroidota','Bacteroidia','Bacteroidales','Tannerellaceae','Tannerella',NULL),
	 (55,'43996','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Catonella',NULL),
	 (56,'44259','Bacillota','Clostridia','Eubacteriales','Peptostreptococcaceae','Filifactor',NULL),
	 (57,'1378','Bacillota','Bacilli','Bacillales','Bacillales Family XI. Incertae Sedis','Gemella',NULL),
	 (58,'437755','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Moryella',NULL),
	 (59,'970','Bacillota','Negativicutes','Selenomonadales','Selenomonadaceae','Selenomonas',NULL),
	 (60,'848','Fusobacteriota','Fusobacteriia','Fusobacteriales','Fusobacteriaceae','Fusobacterium',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (61,'32067','Fusobacteriota','Fusobacteriia','Fusobacteriales','Leptotrichiaceae','Leptotrichia',NULL),
	 (62,'41707','Thermodesulfobacteriota','Desulfovibrionia','Desulfovibrionales','Desulfovibrionaceae','Lawsonia',NULL),
	 (63,'212742','Pseudomonadota','Betaproteobacteria','Neisseriales','Neisseriaceae','Morococcus',NULL),
	 (64,'482','Pseudomonadota','Betaproteobacteria','Neisseriales','Neisseriaceae','Neisseria',NULL),
	 (65,'157','Spirochaetota','Spirochaetia','Spirochaetales','Treponemataceae','Treponema',NULL),
	 (66,'1434006','Synergistota','Synergistia','Synergistales','Aminobacteriaceae','Fretibacterium',NULL),
	 (67,'2093','Mycoplasmatota','Mollicutes','Mycoplasmatales','Mycoplasmataceae','Mycoplasma',NULL),
	 (68,'149698','Pseudomonadota','Betaproteobacteria','Burkholderiales','Oxalobacteraceae','Massilia',NULL),
	 (69,'119060','Pseudomonadota','Betaproteobacteria','Burkholderiales','Burkholderiaceae',NULL,NULL),
	 (70,'82115','Pseudomonadota','Alphaproteobacteria','Hyphomicrobiales','Rhizobiaceae',NULL,NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (71,'186804','Bacillota','Clostridia','Eubacteriales','Peptostreptococcaceae ',NULL,NULL),
	 (72,'818','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides thetaiotaomicron'),
	 (73,'88431','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Dorea','Dorea longicatena'),
	 (74,'1263078','Bacillota','Clostridia','Eubacteriales','Eubacteriaceae','Eubacterium','Eubacterium hallii'),
	 (75,'1265','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Ruminococcus','Ruminococcus favefaciens'),
	 (76,'1304','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus salivarius'),
	 (77,'384636','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Hungatella','Hungatella xylanolytica'),
	 (78,'261299','Bacillota','Clostridia','Eubacteriales','Peptostreptococcaceae','Intestinibacter','Intestinibacter clostridium bartlettii'),
	 (79,'39492','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae',NULL,'Ruminiclostridium eubacterium siraeum'),
	 (80,'84024','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Clostridium','Clostridium disporicum');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (81,'360807','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Roseburia','Roseburia inulinivorans'),
	 (82,'1686','Actinomycetota','Actinomycetes','Bifidobacteriales','Bifidobacteriaceae','Bifidobacterium','Bifdobacterium catenulatum'),
	 (83,'1502','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Clostridium','Clostridium perfringens'),
	 (84,'1073375','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Mediterraneibacter','Blautia ruminococcus gnavus'),
	 (85,'1747','Actinomycetota','Actinomycetes','Propionibacteriales','Propionibacteriaceae','Cutibacterium','Cutibacterium acnes'),
	 (86,'495','Pseudomonadota','Betaproteobacteria','Neisseriales','Neisseriaceae','Neisseria','Neisseria elongata'),
	 (87,NULL,'Pseudomonadota','Gammaproteobacteria','Pseudomonadales','Pseudomonadaceae','Pseudomonas','Pseudomonas sp. IMER-A2-21'),
	 (88,'1344436','Actinomycetota','Actinomycetes','Propionibacteriales','Propionibacteriaceae','Propionibacterium','Propionibacterium sp. MRHull-FeSM-11E'),
	 (89,NULL,'Pseudomonadota','Gammaproteobacteria','Pseudomonadales','Pseudomonadaceae','Pseudomonas','Pseudomonas sp. PS9'),
	 (90,'507807','Pseudomonadota','Betaproteobacteria','Burkholderiales','Comamonadaceae','Variovorax','Variovorax WO3');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (91,'79255','Streptophyta','Magnoliopsida','Ericales','Theaceae','Gordonia',NULL),
	 (92,'28453','Bacteroidota','Sphingobacteriia','Sphingobacteriales','Sphingobacteriaceae','Sphingobacterium ',NULL),
	 (93,'29580','Pseudomonadota','Betaproteobacteria','Burkholderiales','Oxalobacteraceae','Janthinobacterium',NULL),
	 (94,'125216','Pseudomonadota','Alphaproteobacteria','Rhodospirillales','Acetobacteraceae','Roseomonas',NULL),
	 (95,'33882','Actinomycetota','Actinomycetes','Micrococcales','Microbacteriaceae','Microbacterium',NULL),
	 (96,'212791','Pseudomonadota','Gammaproteobacteria','Vibrionales','Vibrionaceae','Enhydrobacter',NULL),
	 (97,'1322','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Blautia','Blautia hansenii'),
	 (98,'418240','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Blautia','Blautia wexlerae'),
	 (99,'102106','Actinomycetota','Coriobacteriia','Coriobacteriales','Coriobacteriaceae','Collinsella',NULL),
	 (100,'74426','Actinomycetota','Coriobacteriia','Coriobacteriales','Coriobacteriaceae','Collinsella','Collinsella aerofaciens');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (101,'239935','Verrucomicrobiota','Verrucomicrobiae','Verrucomicrobiales','Akkermansiaceae ','Akkermansia','Akkermansia muciniphila'),
	 (102,'1150298','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Fusicatenibacter','Fusicatenibacter saccharivorans'),
	 (103,'216816','Actinomycetota','Actinomycetes','Bifidobacteriales','Bifidobacteriaceae','Bifidobacterium','Bifidobacterium longum'),
	 (104,'1680','Actinomycetota','Actinomycetes','Bifidobacteriales','Bifidobacteriaceae','Bifidobacterium','Bifidobacterium adolescentis'),
	 (105,'2173','Euryarchaeota','Methanobacteria','Methanobacteriales','Methanobacteriaceae','Methanobrevibacter','Methanobrevibacter smithii'),
	 (106,'84111','Actinomycetota','Coriobacteriia','Eggerthellales','Eggerthellaceae','Eggerthella',NULL),
	 (107,'186803','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae',NULL,NULL),
	 (108,NULL,'Bacteroidetes','Bacteroidia','Bacteroidales','S24-7',NULL,NULL),
	 (109,'248744','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Marvinbryantia',NULL),
	 (110,NULL,'Bacillota','Clostridia','Clostridiales','Peptococcaceae','rc4-4',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (111,'1849603','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae',NULL,'Enterobacteriaceae bacterium'),
	 (112,'543','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae',NULL,NULL),
	 (113,'547','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Enterobacter',NULL),
	 (114,'964','Pseudomonadota','Betaproteobacteria','Burkholderiales','Oxalobacteraceae','Herbaspirillum','Herbaspirillum seropedicae'),
	 (115,'1280','Bacillota','Bacilli','Bacillales','Staphylococcaceae','Staphylococcus','Staphylococcus aureus'),
	 (116,'128827','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae',NULL,NULL),
	 (117,'817','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides fragilis'),
	 (118,'246787','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides cellulosilyticus'),
	 (119,'371601','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides xylanisolvens'),
	 (120,'1898203','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae',NULL,'Lachnospiraceae bacterium');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (121,'39490','Bacillota','Clostridia','Eubacteriales','Eubacteriaceae','Eubacterium','Eubacterium ramulus'),
	 (122,'487175','Pseudomonadota','Betaproteobacteria','Burkholderiales','Sutterellaceae','Parasutterella','Parasutterella excrementihominis'),
	 (123,'821','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Phocaeicola','Bacteroides vulgatus'),
	 (124,'649756','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Anaerostipes','Anaerostipes hadrus'),
	 (125,'1891238','Pseudomonadota','Betaproteobacteria','Burkholderiales',NULL,NULL,'Burkholderiales bacterium'),
	 (126,'1472417','Bacteroidota','Bacteroidia','Bacteroidales','Odoribacteraceae','Butyricimonas','Butyricimonas paravirosa'),
	 (127,'2479840','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Prevotella','Prevotella marseillensis'),
	 (128,'165179','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Segatella','Segatella copri'),
	 (129,'44748','Bacillota','Clostridia','Eubacteriales','Ruminococcacea','Sporobacter',NULL),
	 (130,'1501226','Bacillota','Clostridia','Eubacteriales','Peptostreptococcaceae','Romboutsia',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (131,'1647','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae','Erysipelothrix',NULL),
	 (132,'712411','Actinomycetota','Coriobacteriia','Coriobacteriales','Atopobiaceae','Olsenella','Olsenella sp. oral taxon 807'),
	 (133,'1508657','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Ruminiclostridium',NULL),
	 (134,'580024','Actinomycetota','Coriobacteriia','Eggerthellales','Eggerthellaceae','Enterorhabdus',NULL),
	 (135,'114627','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Alkaliphilus',NULL),
	 (136,'174708','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae','Allobaculum',NULL),
	 (137,'44249','Bacillota','Bacilli','Bacillales','Paenibacillaceae','Paenibacillus',NULL),
	 (138,'28090','Pseudomonadota','Gammaproteobacteria','Moraxellales','Moraxellaceae','Acinetobacter','Acinetobacter lwoffii'),
	 (139,'626932','Bacteroidota','Bacteroidia','Bacteroidales','Rikenellaceae','Alistipes','Alistipes indistinctus'),
	 (140,'28117','Bacteroidota','Bacteroidia','Bacteroidales','Rikenellaceae','Alistipes','Alistipes putredinis');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (141,'1288121','Bacteroidota','Bacteroidia','Bacteroidales','Rikenellaceae','Alistipes','Alistipes senegalensis'),
	 (142,'419015','Actinomycetota','Actinomycetes','Bifidobacteriales','Bifidobacteriaceae','Alloscardovia','Alloscardovia omnicolens'),
	 (143,'105841','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Anaerostipes','Anaerostipes caccae'),
	 (144,'37921','Actinomycetota','Actinomycetes','Micrococcales','Micrococcaceae','Arthrobacter','Arthrobacter agilis'),
	 (145,'29359','Bacillota','Clostridia','Eubacteriales','Peptostreptococcaceae','Asaccharospora','Asaccharospora irregularis'),
	 (146,'1396','Bacillota','Bacilli','Bacillales','Bacillaceae','Bacillus','Bacillus cereus'),
	 (147,'1399','Bacillota','Bacilli','Bacillales','Bacillaceae','Cytobacillus','Bacillus firmus'),
	 (148,'324768','Bacillota','Bacilli','Bacillales','Bacillaceae','Metabacillus','Bacillus idriensis'),
	 (149,'1402','Bacillota','Bacilli','Bacillales','Bacillaceae','Bacillus','Bacillus licheniformis'),
	 (150,'324854','Bacillota','Bacilli','Bacillales','Bacillaceae','Metabacillus','Bacillus niabensis');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (151,'1423','Bacillota','Bacilli','Bacillales','Bacillaceae','Bacillus','Bacillus subtilis'),
	 (152,'35841','Bacillota','Bacilli','Bacillales','Bacillaceae','Caldibacillus','Bacillus thermoamylovorans'),
	 (153,'291644','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides salyersiae'),
	 (154,'253257','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Lacrimispora','Clostridium amygdalinum'),
	 (155,'1529','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Clostridium','Clostridium cadaveris'),
	 (156,'36841','Bacillota','Clostridia','Eubacteriales','Peptostreptococcaceae','Terrisporobacter','Clostridium glycolicum'),
	 (157,'89153','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Lachnoclostridium','Clostridium hylemonae'),
	 (158,'137838','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Clostridium','Clostridium neonatale'),
	 (159,'1544','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Faecalicatena','Clostridium oroticum'),
	 (160,'29363','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Clostridium','Clostridium paraputrificum');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (161,'84030','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Lacrimispora','Clostridium saccharolyticum'),
	 (162,'1505','Bacillota','Clostridia','Eubacteriales','Peptostreptococcaceae','Paeniclostridium','Clostridium sordellii'),
	 (163,'39950','Bacillota','Negativicutes','Selenomonadales','Veillonellaceae','Dialister','Dialister pneumosintes'),
	 (164,'44009','Bacillota','Bacilli','Lactobacillales','Enterococcaceae','Enterococcus','Enterococcus dispar'),
	 (165,'39483','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae','Faecalitalea','Faecalitalea cylindroides'),
	 (166,'84135','Bacillota','Bacilli','Bacillales','Bacillales Family XI Incertae Sedis','Gemella','Gemella sanguinis'),
	 (167,'1297617','Bacillota','Clostridia','Eubacteriales','Eubacteriales incertae sedis','Intestinimonas','Intestinimonas butyriciproducens'),
	 (168,'152331','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Lactobacillus','Lactobacillus parabuchneri'),
	 (169,'100468','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Schleiferilactobacillus','Lactobacillus perolens'),
	 (170,'176291','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Paucilactobacillus','Lactobacillus vaccinostercus');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (171,'1273','Actinomycetota','Actinomycetes','Micrococcales','Micrococcaceae','Micrococcus','Micrococcus lylae'),
	 (172,'484','Pseudomonadota','Betaproteobacteria','Neisseriales','Neisseriaceae','Neisseria','Neisseria flavescens'),
	 (173,'472695','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Erwiniaceae','Pantoea','Pantoea septica'),
	 (174,'1490','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Paraclostridium','Paraclostridium bifermentans'),
	 (175,'84109','Actinomycetota','Coriobacteriia','Eggerthellales','Eggerthellaceae','Slackia','Slackia exigua'),
	 (176,'1283','Bacillota','Bacilli','Bacillales','Staphylococcaceae','Staphylococcus','Staphylococcus haemolyticus'),
	 (177,'1290','Bacillota','Bacilli','Bacillales','Staphylococcaceae','Staphylococcus','Staphylococcus hominis'),
	 (178,'1343','Bacillota','Bacilli','Bacillales','Staphylococcaceae','Staphylococcus','Streptococcus vestibularis'),
	 (179,'40545','Pseudomonadota','Betaproteobacteria','Burkholderiales','Sutterellaceae','Sutterella','Sutterella wadsworthensis'),
	 (180,'39778','Bacillota','Negativicutes','Selenomonadales','Veillonellaceae','Veillonella','Veillonella dispar');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (181,'1583','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Weissella','Weissella confusa'),
	 (182,'4932','Ascomycota','Saccharomycetes','Saccharomycetales','Saccharomycetaceae','Saccharomyces','Saccharomyces cerevisiae'),
	 (183,'1263','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Ruminococcus',NULL),
	 (184,'620','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Shigella',NULL),
	 (185,'1735','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae','Holdemanella','Holdemanella biformis'),
	 (186,'2005519','Bacteroidota','Bacteroidia','Bacteroidales','Barnesiellaceae',NULL,NULL),
	 (187,'574697','Bacteroidota','Bacteroidia','Bacteroidales','Odoribacteraceae','Butyricimonas',NULL),
	 (188,'171550','Bacteroidota','Bacteroidia','Bacteroidales','Rikenellaceae',NULL,NULL),
	 (189,'2005525','Bacteroidota','Bacteroidia','Bacteroidales','Tannerellaceae','Parabacteroides','Parabacteroides distasonis'),
	 (190,'47678','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides caccae');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (191,'28111','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides eggerthii'),
	 (192,'28116','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides ovatus'),
	 (193,'248039','Deferribacterota','Deferribacteres','Deferribacterales','Mucispirillaceae','Mucispirillum','Mucispirillum schaedleri'),
	 (194,'292632','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Subdoligranulum',NULL),
	 (195,'140625','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Lachnobacterium',NULL),
	 (196,'301302','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Roseburia','Roseburia faecis'),
	 (197,'216572','Bacillota','Clostridia','Eubacteriales','Ruminococcaceae',NULL,NULL),
	 (198,'39948','Bacillota','Negativicutes','Selenomonadales','Veillonellaceae','Dialister',NULL),
	 (199,'100883','Bacillota','Erysipelotrichia','Erysipelotrichales','Coprobacillaceae','Coprobacillus',NULL),
	 (200,'100884','Bacillota','Erysipelotrichia','Erysipelotrichales','Coprobacillaceae','Coprobacillus','Coprobacillus cateniformis');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (201,'61170','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae','Holdemania',NULL),
	 (202,'239934','Verrucomicrobiota','Verrucomicrobiae','Verrucomicrobiales','Akkermansiaceae','Akkermansia',NULL),
	 (203,'31979','Bacillota','Clostridia','Eubacteriales','Clostridiaceae',NULL,NULL),
	 (204,'990719','Bacillota','Clostridia','Eubacteriales','Christensenellaceae',NULL,NULL),
	 (206,'590','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Salmonella',NULL),
	 (207,'84107','Actinomycetota','Coriobacteriia','Coriobacteriales','Coriobacteriaceae',NULL,NULL),
	 (208,'194924','Thermodesulfobacteriota','Desulfovibrionia','Desulfovibrionales','Desulfovibrionaceae',NULL,NULL),
	 (209,'244127','Bacillota','Clostridia','Eubacteriales','Ruminococcaceae','Anaerotruncus',NULL),
	 (210,'577310','Proteobacteria','Betaproteobacteria','Burkholderiales','Alcaligenaceae','Parasutterella',NULL),
	 (211,'1432051','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Eisenbergiella',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (212,'31953','Actinomycetota','Actinomycetes','Bifidobacteriales','Bifidobacteriaceae',NULL,NULL),
	 (213,'1729679','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae','Faecalibaculum',NULL),
	 (214,'1506553','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Lachnoclostridium',NULL),
	 (215,'543311','Bacillota','Clostridia','Clostridiales','FamilyXIIncertaeSedis','Parvimonas',NULL),
	 (216,'653683','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Anaerosporobacter',NULL),
	 (217,'946234','Bacillota','Clostridia','Eubacteriales','Ruminococcaceae','Flavonifractor',NULL),
	 (218,'459786','Bacillota','Clostridia','Eubacteriales','Ruminococcaceae','Oscillibacter',NULL),
	 (219,'35832','Thermodesulfobacteriota','Desulfovibrionia','Desulfovibrionales','Desulfovibrionaceae','Bilophila',NULL),
	 (220,NULL,'Bacillota','Clostridia','Clostridiales','Christensenellaceae','uncultured',NULL),
	 (221,NULL,'Bacillota','Clostridia','Eubacteriales','Peptostreptococcaceae','IncertaeSedis',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (222,'906','Bacillota','Negativicutes','Selenomonadales','Veillonellaceae','Megasphaera',NULL),
	 (223,'561','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Escherichia',NULL),
	 (224,'248038','Deferribacterota','Deferribacteres','Deferribacterales','Mucispirillaceae','Mucispirillum',NULL),
	 (225,'1427378','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Acetatifactor',NULL),
	 (226,'469','Pseudomonadota','Gammaproteobacteria','Moraxellales','Moraxellaceae','Acinetobacter',NULL),
	 (227,'447020','Actinomycetota','Coriobacteriia','Eggerthellales','Eggerthellaceae','Adlercreutzia',NULL),
	 (228,'1386','Bacillota','Bacilli','Bacillales','Bacillaceae','Bacillus',NULL),
	 (229,'904','Bacillota','Negativicutes','Acidaminococcales','Acidaminococcaceae','Acidaminococcus',NULL),
	 (230,'158846','Bacillota','Negativicutes','Selenomonadales','Selenomonadaceae','Megamonas',NULL),
	 (231,'508459','Synergistota','Synergistia','Synergistales','Synergistaceae','Cloacibacillus',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (232,'2172','Euryarchaeota','Methanobacteria','Methanobacteriales','Methanobacteriaceae','Methanobrevibacter',NULL),
	 (233,'46255','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Weissella',NULL),
	 (234,'1350','Bacillota','Bacilli','Lactobacillales','Enterococcaceae','Enterococcus',NULL),
	 (235,'1730','Bacillota','Clostridia','Eubacteriales','Eubacteriaceae','Eubacterium',NULL),
	 (236,'404402','Bacillota','Clostridia','Eubacteriales',NULL,'Howardella',NULL),
	 (237,'209879','Bacillota','Negativicutes','Veillonellales','Veillonellaceae','Allisonella',NULL),
	 (238,'577309','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Paraprevotella',NULL),
	 (239,'5475','Saccharomycotina','Saccharomycetes','Saccharomycetales','Debaryomycetaceae','Candida',NULL),
	 (240,'147550','Ascomycota','Sordariomycetes',NULL,NULL,NULL,NULL),
	 (241,'5073','Eurotiomycetes','Eurotiomycetidae','Eurotiales','Aspergillaceae','Penicillium',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (242,'2005525','Bacteroidota','Bacteroidia','Bacteroidales','Tannerellaceae',NULL,NULL),
	 (243,'851','Fusobacteria','Fusobacteriia','Fusobacteriales','Fusobacteriaceae','Fusobacterium','Fusobacterium nucleatum'),
	 (244,'545','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Citrobacter','Citrobacter koseri'),
	 (245,'53419','Spirochaetes','Spirochaetia','Spirochaetales','Spirochaetaceae','Treponema','Treponema socranskii'),
	 (246,'109328','Fusobacteriota','Fusobacteriia','Fusobacteriales','Leptotrichiaceae','Leptotrichia','Leptotrichia trevisanii'),
	 (247,'89014','Bacillota','Clostridia','Clostridiales','Lachnospiraceae','Blautia','Blautia luti'),
	 (248,'1737424','Bacillota','Clostridia','Clostridiales','Lachnospiraceae','Blautia','Blautia massiliensis'),
	 (249,'40520','Bacillota','Clostridia','Clostridiales','Lachnospiraceae','Blautia','Blautia obeum'),
	 (250,NULL,'Bacillota','Clostridia','Clostridiales','Clostridiaceae_1','Clostridium_sensu_stricto_1','Clostridium_sensu_stricto_1 celatum/disporicum/saudiense'),
	 (251,'39486','Bacillota','Clostridia','Clostridiales','Lachnospiraceae','Dorea','Dorea formicigenerans');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (252,'46503','Bacteroidota','Bacteroidia','Bacteroidales','Tannerellaceae','Parabacteroides','Parabacteroides merdae'),
	 (253,'827','Campylobacterota','Epsilonproteobacteria','Campylobacterales','Campylobacteraceae','Campylobacter','Campylobacter ureolyticus'),
	 (254,'154046','Bacillota','Clostridia','Clostridiales','Lachnospiraceae','Hungatella','Hungatella hathewayi'),
	 (255,'1852382','Bacillota','Clostridia','Clostridiales','Lachnospiraceae','Lachnoclostridium','Lachnoclostridium urinimassiliense'),
	 (256,'45634','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus cristatus/sanguinis'),
	 (257,'322095','Bacteroidetes','Bacteroidia','Bacteroidales','Porphyromonadaceae','Porphyromonas','Porphyromonas somerae'),
	 (258,'33033','Bacillota','Clostridia','Clostridiales','Family_XI','Parvimonas','Parvimonas micra'),
	 (259,'29391','Bacillota','Bacilli','Bacillales','Family_XI','Gemella','Gemella morbillorum'),
	 (260,'824','Campylobacterota','Epsilonproteobacteria','Campylobacterales','Campylobacteraceae','Campylobacter','Campylobacter gracilis'),
	 (261,'1917870','Bacillota','Clostridia','Clostridiales','Lachnospiraceae','Lachnoclostridium','Lachnoclostridium pacaense');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (262,NULL,'Bacillota','Clostridia','Eubacteriales','Ruminococcaceae','Ruminococcaceae_UCG-002','Ruminococcaceae_UCG-002 bacterium'),
	 (263,'1547','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae','Erysipelatoclostridium','Erysipelatoclostridium ramosum'),
	 (264,'100886','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae','Catenibacterium','Catenibacterium mitsuokai'),
	 (265,'40518','Bacillota','Clostridia','Eubacteriales','Ruminococcaceae','Ruminococcus','Ruminococcus bromii'),
	 (266,'2047','Actinomycetota','Actinomycetes','Micrococcales','Micrococcaceae','Rothia','Rothia dentocariosa'),
	 (267,'43768','Actinomycetota','Actinomycetes','Corynebacteriales','Corynebacteriaceae','Corynebacterium','Corynebacterium matruchotii'),
	 (268,'38303','Actinomycetota','Actinomycetes','Corynebacteriales','Corynebacteriaceae','Corynebacterium_1','Corynebacterium pseudogenitalium'),
	 (269,'69823','Bacillota','Negativicutes','Selenomonadales','Veillonellaceae','Selenomonas','Selenomonas sputigena'),
	 (270,'1328','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus anginosus/milleri/mitis'),
	 (271,'644652','Actinomycetota','Coriobacteriia','Eggerthellales','Eggerthellaceae','Gordonibacter',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (272,'2717','Pseudomonadota','Gammaproteobacteria','Cardiobacteriales','Cardiobacteriaceae','Cardiobacterium',NULL),
	 (273,'1380','Actinomycetota','Coriobacteriia','Coriobacteriales','Atopobiaceae','Atopobium',NULL),
	 (274,'196081','Actinomycetota','Actinomycetes','Bifidobacteriales','Bifidobacteriaceae','Scardovia',NULL),
	 (275,'86331','Bacillota','Clostridia','Eubacteriales','Eubacteriales Family XIII. Incertae Sedis','Mogibacterium',NULL),
	 (276,'1224','Proteobacteria',NULL,NULL,NULL,NULL,NULL),
	 (277,'201174','Actinomycetota',NULL,NULL,NULL,NULL,NULL),
	 (278,'416916','Pseudomonadota','Gammaproteobacteria','Pasteurellales','Pasteurellaceae','Aggregatibacter',NULL),
	 (279,'59735','Bacteroidota','Flavobacteriia','Flavobacteriales','Weeksellaceae','Bergeyella',NULL),
	 (280,'363464','Gracilibacteria',NULL,NULL,NULL,NULL,NULL),
	 (281,'33038','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Mediterraneibacter','[Ruminococcus] gnavus');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (282,'1317','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus downei'),
	 (283,'739','Pseudomonadota','Gammaproteobacteria','Pasteurellales','Pasteurellaceae','Aggregatibacter','Aggregatibacter segnis'),
	 (284,'147207','Actinomycetota','Coriobacteriia','Coriobacteriales','Coriobacteriaceae','Collinsella','Collinsella intestinalis'),
	 (285,'861','Fusobacteria','Fusobacteriia','Fusobacteriales','Fusobacteriaceae','Fusobacterium','Fusobacterium ulcerans'),
	 (286,'856','Fusobacteria','Fusobacteriia','Fusobacteriales','Fusobacteriaceae','Fusobacterium','Fusobacterium varium'),
	 (287,'28123','Bacteroidota','Bacteroidia','Bacteroidales','Porphyromonadaceae','Porphyromonas','Porphyromonas asaccharolytica'),
	 (288,'837','Bacteroidota','Bacteroidia','Bacteroidales','Porphyromonadaceae','Porphyromonas','Porphyromonas gingivalis'),
	 (289,'290053','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides helcogenes'),
	 (290,'884684','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Mageeibacillus','Clostridiales genomosp. BVAB3'),
	 (291,'29348','Bacillota','Erysipelotrichia','Erysipelotrichales','Coprobacillaceae','Thomasclavelia','Clostridium spiroforme');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (292,'1303','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus oralis'),
	 (293,'487','Pseudomonadota','Betaproteobacteria','Neisseriales','Neisseriaceae','Neisseria','Neisseria meningitidis'),
	 (294,'351091','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Oscillibacter','Oscillibacter valericigenes'),
	 (295,'33871','Actinomycetota','Coriobacteriia','Coriobacteriales','Coriobacteriaceae','Coriobacterium','Coriobacterium glomerans'),
	 (296,'732','Pseudomonadota','Gammaproteobacteria','Pasteurellales','Pasteurellaceae','Aggregatibacter','Aggregatibacter aphrophilus'),
	 (297,'28118','Bacteroidota','Bacteroidia','Marinilabiliales','Marinifilaceae','Odoribacter','Odoribacter splanchnicus'),
	 (298,'410072','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Coprococcus','Coprococcus comes'),
	 (299,'147206','Actinomycetota','Coriobacteriia','Coriobacteriales','Coriobacteriaceae','Collinsella','Collinsella stercoris'),
	 (300,'483','Pseudomonadota','Betaproteobacteria','Neisseriales','Neisseriaceae','Neisseria','Neisseria cinerea'),
	 (301,'33039','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Mediterraneibacter','[Ruminococcus] torques');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (302,'28449','Pseudomonadota','Betaproteobacteria','Neisseriales','Neisseriaceae','Neisseria','Neisseria subflava'),
	 (303,'1352','Bacillota','Bacilli','Lactobacillales','Enterococcaceae','Enterococcus','Enterococcus faecium'),
	 (304,'31971','Bacillota','Clostridia','Eubacteriales','Eubacteriaceae','Eubacterium','Eubacterium dolichum'),
	 (305,'490','Pseudomonadota','Betaproteobacteria','Neisseriales','Neisseriaceae','Neisseria','Neisseria sicca/macacae'),
	 (306,'626929','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides clarus'),
	 (307,'228654','Pseudomonadota','Gammaproteobacteria','Moraxellales','Moraxellaceae','Psychrobacter','Psychrobacter pulmonis'),
	 (309,'129817','Pseudomonadota','Gammaproteobacteria','Pseudomonadales','Pseudomonadaceae','Pseudomonas','Pseudomonas brenneri'),
	 (310,'985266','Pseudomonadota','Gammaproteobacteria','Moraxellales','Moraxellaceae','Moraxella','Moraxella sp. S2'),
	 (311,NULL,NULL,NULL,NULL,NULL,'1-68',NULL),
	 (312,'162289','Bacillota','Tissierellia','Tissierellales','Peptoniphilaceae','Peptoniphilus',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (313,NULL,NULL,NULL,NULL,NULL,'WAL_1855D',NULL),
	 (314,'165779','Bacillota','Tissierellia','Tissierellales','Peptoniphilaceae','Anaerococcus',NULL),
	 (315,'1643826','Actinomycetota','Coriobacteriia','Eggerthellales','Eggerthellaceae',NULL,NULL),
	 (316,NULL,'Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','UBA738','UBA738 sp003522945'),
	 (317,NULL,NULL,NULL,NULL,NULL,NULL,'ER4 sp000765235'),
	 (318,NULL,'Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','CAG-83',NULL),
	 (319,NULL,NULL,NULL,NULL,'Acutalibacteraceae','CAG-217','CAG-217 sp000436335'),
	 (320,'39485','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Lachnospira','Lachnospira eligens'),
	 (321,'487174','Bacteroidota','Bacteroidia','Bacteroidales','Barnesiellaceae','Barnesiella','Barnesiella intestinihominis'),
	 (322,'454154','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Paraprevotella','Paraprevotella clara');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (323,NULL,NULL,NULL,NULL,'Acutalibacteraceae','CAG-180','CAG-180 sp000432435'),
	 (324,'1623','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Ligilactobacillus','Ligilactobacillus ruminis'),
	 (325,'1599','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Latilactobacillus','Latilactobacillus sakei'),
	 (326,'1937008','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae','Dubosiella',NULL),
	 (327,'2740','Bacillota','Clostridia','Eubacteriales','Peptococcaceae','Peptococcus',NULL),
	 (328,'1643824','Actinomycetota','Coriobacteriia','Coriobacteriales','Atopobiaceae',NULL,NULL),
	 (329,'91061','Bacillota','Bacilli',NULL,NULL,NULL,NULL),
	 (330,'562','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Escherichia','Escherichia coli'),
	 (331,'1318','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus parasanguinis'),
	 (332,'1596','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Lactobacillus','Lactobacillus gasseri');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (333,'1613','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Lactobacillus','Lactobacillus fermentum'),
	 (334,'186532','Uroviricota','Caudoviricetes',NULL,NULL,'c2-like viruses',NULL),
	 (335,'1535','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Clostridium','[Clostridium] leptum '),
	 (336,'328812','Bacteroidota','Bacteroidia','Bacteroidales','Tannerellaceae','Parabacteroides','Parabacteroides goldsteinii'),
	 (337,'1689','Actinomycetota','Actinomycetes','Bifidobacteriales','Bifidobacteriaceae','Bifidobacterium','Bifidobacterium dentium'),
	 (338,'2049044','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae',NULL,'Erysipelotrichaceae bacterium'),
	 (339,'208479','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Enterocloster','Clostridium bolteae'),
	 (340,'729','Pseudomonadota','Gammaproteobacteria','Pasteurellales','Pasteurellaceae','Haemophilus','Haemophilus parainfluenzae'),
	 (341,'546','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Citrobacter ','Citrobacter freundii'),
	 (342,'544','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Citrobacter',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (343,'1351','Bacillota','Bacilli','Lactobacillales','Enterococcaceae','Enterococcus','Enterococcus faecalis'),
	 (344,'200643','Bacteroidota','Bacteroidia',NULL,NULL,NULL,NULL),
	 (345,'2030927','Bacteroidota','Bacteroidia','Bacteroidales',NULL,NULL,'Bacteroidales bacterium'),
	 (346,'315405','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus gallolyticus'),
	 (347,'68891','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus peroris'),
	 (348,'437897','Bacillota','Negativicutes','Selenomonadales','Selenomonadaceae','Megamonas','Megamonas funiformis'),
	 (349,'33945','Bacillota','Bacilli','Lactobacillales','Enterococcaceae','Enterococcus','Enterococcus avium'),
	 (350,'1390','Bacillota','Bacilli','Bacillales','Bacillaceae','Bacillus','Bacillus amyloliquefaciens'),
	 (351,'189382','Bacillota','Bacilli','Bacillales','Bacillaceae','Bacillus','Bacillus aquimaris'),
	 (352,'86668','Bacillota','Bacilli','Bacillales','Bacillaceae','Bacillus','Bacillus niacini');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (353,'38875','Bacillota','Bacilli','Bacillales','Bacillaceae','Bacillus','Bacillus oleronius'),
	 (354,'29356','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Clostridium','Clostridium chartatabidum'),
	 (355,'97253','Bacillota','Clostridia','Eubacteriales','Eubacteriaceae','Eubacterium','Eubacterium plexicaudatum'),
	 (356,'61171','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae','Holdemania','Holdemania filiformis'),
	 (357,'288966','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Lutispora','Lutispora thermophila'),
	 (358,'682400','Bacillota','Clostridiales','Eubacteriales',NULL,'Natranaerovirga','Natranaerovirga pectinivora'),
	 (359,'28129','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Prevotella','Prevotella denticola'),
	 (360,'840','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Prevotella','Prevotella loescheii'),
	 (361,'28134','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Prevotella','Prevotella oralis'),
	 (362,'28135','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Prevotella','Prevotella oris');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (363,'363265','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Prevotella','Prevotella stercorea'),
	 (364,'40519','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Ruminococcus','Ruminococcus callidus'),
	 (365,'1338','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus intermedius'),
	 (366,'55565','Actinomycetota','Actinomycetes','Actinomycetales','Actinomycetaceae','Actinomyces','Actinomyces graevenitzii'),
	 (367,'1655','Actinomycetota','Actinomycetes','Actinomycetales','Actinomycetaceae','Actinomyces','Actinomyces naeslundii'),
	 (368,'446660','Actinomycetota','Coriobacteriia','Eggerthellales','Eggerthellaceae','Adlercreutzia','Adlercreutzia equolifaciens'),
	 (369,'36839','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Clostridium','Clostridium aurantibutyricum'),
	 (370,'116085','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Coprococcus','Coprococcus catus'),
	 (371,'471189','Actinomycetota','Coriobacteriia','Eggerthellales','Eggerthellaceae','Gordonibacter','Gordonibacter pamelaeae'),
	 (372,'166486','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Roseburia','Roseburia intestinalis');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (373,'114702','Actinomycetota','Actinomycetes','Actinomycetales','Actinomycetaceae','Actinomyces','Actinomyces lingnae'),
	 (374,'1405','Bacillota','Bacilli','Bacillales','Bacillaceae','Bacillus','Bacillus mycoides'),
	 (375,'99656','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Lachnoclostridium','[Clostridium] fimetarium'),
	 (376,NULL,'Bacillota','Clostridia','Eubacteriales','Peptostreptococcaceae','Terrisporobacter','Clostridium metallolevans'),
	 (377,'33043','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Coprococcus','Coprococcus eutactus'),
	 (378,'384639','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides galacturonicus'),
	 (379,'4892','Ascomycota','Saccharomycetes','Saccharomycetales',NULL,NULL,NULL),
	 (380,'5204','Basidiomycota',NULL,NULL,NULL,NULL,NULL),
	 (381,NULL,NULL,NULL,'RF39',NULL,NULL,NULL),
	 (382,'2937909','Bacillota','Clostridia','Eubacteriales','Desulfitobacteriaceae',NULL,NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (383,'186802','Bacillota','Clostridia','Clostridiales',NULL,NULL,NULL),
	 (384,NULL,NULL,NULL,NULL,NULL,'SMB53',NULL),
	 (385,NULL,NULL,NULL,NULL,'Gemellaceae',NULL,NULL),
	 (386,'171549','Bacteroidota','Bacteroidia','Bacteroidales',NULL,NULL,NULL),
	 (387,'35493','Streptophyta',NULL,NULL,NULL,NULL,NULL),
	 (388,'57037','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Lacticaseibacillus','Lacticaseibacillus zeae'),
	 (389,'33035','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Blautia','Blautia producta'),
	 (390,'29466','Bacillota','Negativicutes','Veillonellales','Veillonellaceae','Veillonella','Veillonella parvula'),
	 (391,NULL,'Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae','cc_115',NULL),
	 (392,'468','Pseudomonadota','Gammaproteobacteria','Moraxellales','Moraxellaceae',NULL,NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (393,'186806','Bacillota','Clostridia','Eubacteriales','Eubacteriaceae',NULL,NULL),
	 (394,'1239','Bacillota',NULL,NULL,NULL,NULL,NULL),
	 (395,'186333','Mycoplasmatota','Mollicutes','Anaeroplasmatales','Anaeroplasmataceae',NULL,NULL),
	 (396,'204431','Fibrobacterota','Fibrobacteria','Fibrobacterales','Fibrobacteraceae',NULL,NULL),
	 (397,'2767887','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Ligilactobacillus',NULL),
	 (398,'1918542','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Muricomes',NULL),
	 (399,'191394','Deferribacterota','Deferribacteres','Deferribacterales','Deferribacteraceae',NULL,NULL),
	 (400,'2039302','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Monoglobus',NULL),
	 (401,'1905344','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Ruthenibacterium',NULL),
	 (402,'1929083','Bacteroidota','Bacteroidia','Bacteroidales','Rikenellaceae','Tidjanibacter',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (403,'1357','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Lactococcus',NULL),
	 (404,'57723','Acidobacteriota',NULL,NULL,NULL,NULL,NULL),
	 (405,'28025','Actinomycetota','Actinomycetes','Bifidobacteriales','Bifidobacteriaceae','Bifidobacterium','Bifidobacterium animalis'),
	 (406,'186828','Bacillota','Bacilli','Lactobacillales','Carnobacteriaceae',NULL,NULL),
	 (407,'1653','Actinomycetota','Actinomycetes','Mycobacteriales','Corynebacteriaceae',NULL,NULL),
	 (408,'246874','Bacteroidota','Flavobacteriia','Flavobacteriales','Cryomorphaceae',NULL,NULL),
	 (409,'33958','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae',NULL,NULL),
	 (410,'1268','Actinomycetota','Actinomycetes','Micrococcales','Micrococcaceae',NULL,NULL),
	 (411,'815','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae',NULL,NULL),
	 (412,'171552','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae',NULL,NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (413,'135621','Pseudomonadota','Gammaproteobacteria','Pseudomonadales','Pseudomonadaceae',NULL,NULL),
	 (414,'1760','Actinomycetota','Actinomycetes',NULL,NULL,NULL,NULL),
	 (415,'28211','Pseudomonadota','Alphaproteobacteria',NULL,NULL,NULL,NULL),
	 (416,'28216','Pseudomonadota','Betaproteobacteria',NULL,NULL,NULL,NULL),
	 (417,'1236','Pseudomonadota','Gammaproteobacteria',NULL,NULL,NULL,NULL),
	 (418,'186826','Bacillota','Bacilli','Lactobacillales',NULL,NULL,NULL),
	 (419,'80840','Pseudomonadota','Betaproteobacteria','Burkholderiales',NULL,NULL,NULL),
	 (420,'91347','Pseudomonadota','Gammaproteobacteria','Enterobacterales',NULL,NULL,NULL),
	 (421,'236752','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Fastidiosipila',NULL),
	 (422,'1297','Deinococcota',NULL,NULL,NULL,NULL,NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (423,'85015','Actinomycetota','Actinomycetes','Propionibacteriales','Nocardioidaceae',NULL,NULL),
	 (424,'183710','Deinococcota','Deinococci','Deinococcales','Deinococcaceae',NULL,NULL),
	 (425,'45404','Pseudomonadota','Alphaproteobacteria','Hyphomicrobiales','Beijerinckiaceae',NULL,NULL),
	 (426,'74201','Verrucomicrobia',NULL,NULL,NULL,NULL,NULL),
	 (427,'186801','Bacillota','Clostridia',NULL,NULL,NULL,NULL),
	 (428,'909932','Bacillota','Negativicutes',NULL,NULL,NULL,NULL),
	 (429,'203494','Verrucomicrobiota','Verrucomicrobiae',NULL,NULL,NULL,NULL),
	 (430,'909929','Bacillota','Negativicutes','Selenomonadales',NULL,NULL,NULL),
	 (431,'48461','Verrucomicrobiota','Verrucomicrobiae','Verrucomicrobiales',NULL,NULL,NULL),
	 (432,'31977','Bacillota','Negativicutes','Veillonellales','Veillonellaceae',NULL,NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (433,'203557','Verrucomicrobiota','Verrucomicrobiae','Verrucomicrobiales','Verrucomicrobiaceae',NULL,NULL),
	 (434,'171551','Bacteroidota','Bacteroidia','Bacteroidales','Porphyromonadaceae',NULL,NULL),
	 (435,'909930','Bacillota','Negativicutes','Acidaminococcales','Acidaminococcaceae',NULL,NULL),
	 (436,NULL,'Bacillota','Clostridia','Clostridiales','Lachnospiraceae','Lachnospiraceae UCG-001',NULL),
	 (437,'1816687','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Massiliprevotella','Massiliprevotella massiliensis'),
	 (438,'13690','Pseudomonadota','Alphaproteobacteria','Sphingomonadales','Sphingomonadaceae','Sphingobium','Sphingobium yanoikuyae'),
	 (439,'13687','Pseudomonadota','Alphaproteobacteria','Sphingomonadales','Sphingomonadaceae','Sphingomonas',NULL),
	 (440,'914','Pseudomonadota','Betaproteobacteria','Nitrosomonadales','Nitrosomonadaceae','Nitrosomonas',NULL),
	 (441,'82976','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Buttiauxella',NULL),
	 (442,'48935','Pseudomonadota','Alphaproteobacteria','Sphingomonadales','Sphingomonadaceae','Novosphingobium','Novosphingobium aromaticivorans');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (443,'374','Pseudomonadota','Alphaproteobacteria','Hyphomicrobiales','Nitrobacteraceae','Bradyrhizobium',NULL),
	 (444,'257758','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus pseudopneumoniae'),
	 (445,'31998','Pseudomonadota','Alphaproteobacteria','Hyphomicrobiales','Methylobacteriaceae','Methylobacterium','Methylobacterium radiotolerans'),
	 (446,'407','Pseudomonadota','Alphaproteobacteria','Hyphomicrobiales','Methylobacteriaceae','Methylobacterium',NULL),
	 (447,'237','Bacteroidota','Flavobacteriia','Flavobacteriales','Flavobacteriaceae','Flavobacterium',NULL),
	 (448,'1309','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus mutans'),
	 (449,'2037','Actinomycetota','Actinomycetes','Actinomycetales',NULL,NULL,NULL),
	 (450,'543314','Bacillota','Clostridia','Eubacteriales','Eubacteriales Family XIII. Incertae Sedis',NULL,NULL),
	 (451,'2049','Actinomycetota','Actinomycetes','Actinomycetales','Actinomycetaceae',NULL,NULL),
	 (452,'186822','Bacillota','Bacilli','Bacillales','Paenibacillaceae',NULL,NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (453,'84993','Actinomycetota','Acidimicrobiia','Acidimicrobiales',NULL,NULL,NULL),
	 (454,'1385','Bacillota','Bacilli','Bacillales',NULL,NULL,NULL),
	 (455,NULL,'Actinomycetota','Actinomycetes','0319-7L14',NULL,NULL,NULL),
	 (456,NULL,'Firmicutes','Clostridia','OPB54',NULL,NULL,NULL),
	 (457,'31980','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Acetitomaculum',NULL),
	 (458,'66851','Euryarchaeota','Methanobacteria','Methanobacteriales','Methanobacteriaceae','Methanobrevibacter','Methanobrevibacter oralis'),
	 (459,'1321783','Bacillota','Clostridia','Eubacteriales','Peptostreptococcaceae',NULL,'Peptostreptococcaceae bacterium oral taxon 113'),
	 (460,'29465','Bacillota','Negativicutes','Veillonellales','Veillonellaceae','Veillonella',NULL),
	 (461,'1685','Actinomycetota','Actinomycetes','Bifidobacteriales','Bifidobacteriaceae','Bifidobacterium','Bifidobacterium breve'),
	 (462,'29521','Spirochaetota','Spirochaetia','Brachyspirales','Brachyspiraceae','Brachyspira',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (463,'454155','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Paraprevotella','Paraprevotella xylaniphila'),
	 (464,'384638','Bacillota','Clostridia','Eubacteriales',NULL,NULL,'[Bacteroides] pectinophilus'),
	 (465,'69966','Bacillota','Bacilli','Bacillales','Staphylococcaceae','Macrococcus','Macrococcus caseolyticus'),
	 (466,'160386','Actinomycetota','Actinomycetes','Mycobacteriales','Corynebacteriaceae','Corynebacterium','Corynebacterium casei'),
	 (467,'1649','Bacillota','Bacilli','Bacillales','Planococcaceae','Kurthia',NULL),
	 (468,'1605','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Ligilactobacillus','Ligilactobacillus animalis'),
	 (469,'658083','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae',NULL,'Lachnospiraceae bacterium 6_1_63FAA'),
	 (470,'310298','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Phocaeicola','Phocaeicola coprocola'),
	 (471,'57493','Actinomycetota','Actinomycetes','Micrococcales','Micrococcaceae','Kocuria',NULL),
	 (472,'152794','Actinomycetota','Actinomycetes','Mycobacteriales','Corynebacteriaceae','Corynebacterium','Corynebacterium efficiens');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (473,'53346','Bacillota','Bacilli','Lactobacillales','Enterococcaceae','Enterococcus','Enterococcus mundtii'),
	 (474,'394098','Bacillota','Bacilli','Bacillales','Planococcaceae','Bhargavaea','Bhargavaea cecembensis'),
	 (475,'552395','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae',NULL,'Lachnospiraceae bacterium 4_1_37FAA'),
	 (476,'592377','Actinomycetota','Actinomycetes','Micrococcales','Micrococcaceae','Kocuria','Kocuria atrinae'),
	 (477,'1354','Bacillota','Bacilli','Lactobacillales','Enterococcaceae','Enterococcus','Enterococcus hirae'),
	 (478,'1308','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus thermophilus'),
	 (479,'72000','Actinomycetota','Actinomycetes','Micrococcales','Micrococcaceae','Kocuria','Kocuria rhizophila'),
	 (480,'1161942','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Ruminococcus','Ruminococcus champanellensis'),
	 (481,'45669','Bacillota','Bacilli','Bacillales','Staphylococcaceae','Salinicoccus',NULL),
	 (482,'265976','Actinomycetota;','Actinomycetes','Micrococcales','Ornithinimicrobiaceae','Serinicoccus',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (483,'1428','Bacillota','Bacilli','Bacillales','Bacillaceae','Bacillus','Bacillus thuringiensis'),
	 (484,'575200','Actinomycetota','Actinomycetes','Mycobacteriales','Corynebacteriaceae','Corynebacterium','Corynebacterium maris'),
	 (485,'321318','Actinomycetota','Actinomycetes','Mycobacteriales','Dietziaceae','Dietzia','Dietzia cinnamea'),
	 (486,'1622','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Ligilactobacillus','Ligilactobacillus murinus'),
	 (487,'414778','Bacillota','Bacilli','Bacillales','Planococcaceae','Planococcus','Planococcus donghaensis'),
	 (488,'106588','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Pseudoflavonifractor','Pseudoflavonifractor capillosus'),
	 (489,'469610','Pseudomonadota','Betaproteobacteria','Burkholderiales',NULL,NULL,'Burkholderiales bacterium 1_1_47'),
	 (490,'658657','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae',NULL,'Erysipelotrichaceae bacterium 21_3'),
	 (491,'169435','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Anaerotruncus','Anaerotruncus colihominis'),
	 (492,'204516','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Phocaeicola','Phocaeicola massiliensis');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (493,'457422','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae',NULL,'Erysipelotrichaceae bacterium 2_2_44A'),
	 (494,'333367','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Enterocloster','Enterocloster asparagiformis'),
	 (495,'469614','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae',NULL,'Erysipelotrichaceae bacterium 6_1_45'),
	 (496,'658087','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae',NULL,'Lachnospiraceae bacterium 7_1_58FAA'),
	 (497,'328813','Bacteroidota','Bacteroidia','Bacteroidales','Rikenellaceae','Alistipes','Alistipes onderdonkii'),
	 (498,'292800','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Flavonifractor','Flavonifractor plautii'),
	 (499,'214856','Bacteroidota','Bacteroidia','Bacteroidales','Rikenellaceae','Alistipes','Alistipes finegoldii'),
	 (500,'137591','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Weissella','Weissella cibaria'),
	 (501,'1270','Actinomycetota','Actinomycetes','Micrococcales','Micrococcaceae','Micrococcus','Micrococcus luteus'),
	 (502,'550','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Enterobacter','Enterobacter cloacae');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (503,'133925','Actinomycetota','Coriobacteriia','Coriobacteriales','Atopobiaceae','Olsenella',NULL),
	 (504,'624','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Shigella','Shigella sonnei'),
	 (505,'626940','Bacillota','Negativicutes','Acidaminococcales','Acidaminococcaceae','Phascolarctobacterium','Phascolarctobacterium succinatutens'),
	 (506,'45851','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Butyrivibrio','Butyrivibrio crossotus'),
	 (507,'32008','Pseudomonadota','Betaproteobacteria','Burkholderiales','Burkholderiaceae','Burkholderia',NULL),
	 (508,'901','Thermodesulfobacteriota','Desulfovibrionia','Desulfovibrionales','Desulfovibrionaceae','Desulfovibrio','Desulfovibrio piger'),
	 (509,'97478','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Limosilactobacillus','Limosilactobacillus mucosae'),
	 (510,'43675','Actinomycetota','Actinomycetes','Micrococcales','Micrococcaceae','Rothia','Rothia mucilaginosa'),
	 (511,'150055','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus lutetiensis'),
	 (512,'102684','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus infantarius');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (513,'1363','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Lactococcus','Lactococcus garvieae'),
	 (514,'47671','Pseudomonadota','Betaproteobacteria','Burkholderiales','Burkholderiaceae','Lautropia','Lautropia mirabilis'),
	 (515,'59310','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus macedonicus'),
	 (516,'197','Campylobacterota','Epsilonproteobacteria','Campylobacterales','Campylobacteraceae','Campylobacter','Campylobacter jejuni'),
	 (517,'197614','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus pasteurianus'),
	 (518,'167','Spirochaetota','Spirochaetia','Spirochaetales','Treponemataceae','Treponema','Treponema succinifaciens'),
	 (519,'37372','Campylobacterota','Epsilonproteobacteria','Campylobacterales','Helicobacteraceae','Helicobacter','Helicobacter bilis'),
	 (520,'213','Campylobacterota','Epsilonproteobacteria','Campylobacterales','Helicobacteraceae','Helicobacter','Helicobacter cinaedi'),
	 (521,'53443','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Blautia','Blautia hydrogenotrophica'),
	 (522,'658085','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae',NULL,'Lachnospiraceae bacterium 5_1_57FAA');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (523,'552396','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae',NULL,'Erysipelotrichaceae bacterium 5_2_54FAA'),
	 (524,'1226322','Clostridia','Eubacteriales','Oscillospiraceae','Oscillibacter',NULL,'Oscillibacter sp. KLE 1728'),
	 (525,'85698','Pseudomonadota','Betaproteobacteria','Burkholderiales','Alcaligenaceae','Achromobacter','Achromobacter xylosoxidans'),
	 (526,'501571','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Butyricicoccus','Butyricicoccus pullicaecorum'),
	 (527,'84026','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae',NULL,'[Clostridium] methylpentosum'),
	 (528,'649724','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Clostridium','Clostridium sp. ATCC BAA-442'),
	 (529,'1833','Actinomycetota','Actinomycetes','Mycobacteriales','Nocardiaceae','Rhodococcus','Rhodococcus erythropolis'),
	 (530,'1226325','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Clostridium','Clostridium sp. KLE 1755'),
	 (531,'626935','Actinomycetota','Coriobacteriia','Coriobacteriales','Coriobacteriaceae','Collinsella','Collinsella tanakaei'),
	 (532,'1468449','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae','Holdemania','Holdemania massiliensis');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (533,'469613','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae',NULL,'Enterobacteriaceae bacterium 9_2_54FAA'),
	 (534,'28038','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Latilactobacillus','Latilactobacillus curvatus'),
	 (535,'1744','Actinomycetota','Actinomycetes','Propionibacteriales','Propionibacteriaceae','Propionibacterium','Propionibacterium freudenreichii'),
	 (536,'376805','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Phocaeicola','Phocaeicola salanitronis'),
	 (537,'47715','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Lacticaseibacillus','Lacticaseibacillus rhamnosus'),
	 (538,'1252','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Leuconostoc','Leuconostoc carnosum'),
	 (539,'457402','Bacillota','Clostridia','Eubacteriales','Eubacteriaceae','Eubacterium','Eubacterium sp. 3_1_31'),
	 (540,'1531','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Enterocloster','Enterocloster clostridioformis'),
	 (541,'658659','Bacillota','Erysipelotrichia','Erysipelotrichales','Erysipelotrichaceae',NULL,'Erysipelotrichaceae bacterium 3_1_53'),
	 (542,'472761','Actinomycetota','Coriobacteriia','Coriobacteriales','Coriobacteriaceae','Enorma','Enorma massiliensis');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (543,'1099853','Bacteroidota','Bacteroidia','Bacteroidales','Barnesiellaceae','Coprobacter','Coprobacter fastidiosus'),
	 (544,'457421','Bacillota','Clostridia','Eubacteriales',NULL,NULL,'Clostridiales bacterium 1_7_47FAA'),
	 (545,'908612','Bacteroidota','Bacteroidia','Bacteroidales','Rikenellaceae','Alistipes','Alistipes sp. HGB5'),
	 (546,'29347','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Lachnoclostridium','[Clostridium] scindens'),
	 (547,'1226323','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Oscillibacter','Oscillibacter sp. KLE 1745'),
	 (548,'222','Pseudomonadota','Betaproteobacteria','Burkholderiales','Alcaligenaceae','Achromobacter',NULL),
	 (549,'665956','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Subdoligranulum','Subdoligranulum sp. 4_3_54A2FAA'),
	 (551,'1470347','Bacteroidota','Bacteroidia','Bacteroidales','Rikenellaceae','Alistipes','Alistipes ihumii'),
	 (552,'552398','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae',NULL,'Ruminococcaceae bacterium D16'),
	 (553,'658655','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae',NULL,'Lachnospiraceae bacterium 1_4_56FAA');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (554,'658086','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae',NULL,'Lachnospiraceae bacterium 3_1_57FAA_CT1'),
	 (555,'72274','Pseudomonadota','Gammaproteobacteria','Pseudomonadales',NULL,NULL,NULL),
	 (556,'85004','Actinomycetota','Actinomycetes','Bifidobacteriales',NULL,NULL,NULL),
	 (557,'85006','Actinomycetota','Actinomycetes','Micrococcales',NULL,NULL,NULL),
	 (558,'976','Bacteroidota',NULL,NULL,NULL,NULL,NULL),
	 (559,'1070699','Bacillota','Clostridia','Eubacteriales','Clostridiaceae',NULL,'Clostridiaceae bacterium JC118'),
	 (560,'72556','Pseudomonadota','Betaproteobacteria','Burkholderiales','Alcaligenaceae','Achromobacter','Achromobacter piechaudii'),
	 (561,'1522','Bacillota','Erysipelotrichia','Erysipelotrichales','Coprobacillaceae','Thomasclavelia','[Clostridium] innocuum'),
	 (562,'658088','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae',NULL,'Lachnospiraceae bacterium 9_1_43BFAA'),
	 (563,'218538','Bacillota','Negativicutes','Veillonellales','Veillonellaceae','Dialister','Dialister invisus');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (564,'665950','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae',NULL,'Lachnospiraceae bacterium 3_1_46FAA'),
	 (565,'1512','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Lachnoclostridium','[Clostridium] symbiosum'),
	 (566,'1584','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Lactobacillus','Lactobacillus delbrueckii'),
	 (567,'358743','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Enterocloster','Enterocloster citroniae'),
	 (568,'1245','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Leuconostoc','Leuconostoc mesenteroides'),
	 (569,'214853','Bacillota','Clostridia','Eubacteriales','Eubacteriaceae','Anaerofustis','Anaerofustis stercorihominis'),
	 (570,'517','Pseudomonadota','Betaproteobacteria','Burkholderiales','Alcaligenaceae','Bordetella',NULL),
	 (571,'310297','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Phocaeicola','Phocaeicola plebeius'),
	 (572,'357276','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Phocaeicola','Phocaeicola dorei'),
	 (573,'34072','Pseudomonadota','Betaproteobacteria','Burkholderiales','Comamonadaceae','Variovorax',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (574,'544644','Bacteroidota','Bacteroidia','Bacteroidales','Odoribacteraceae','Butyricimonas','Butyricimonas synergistica'),
	 (575,'658081','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae',NULL,'Lachnospiraceae bacterium 1_1_57FAA
'),
	 (576,'84112','Actinomycetota','Coriobacteriia','Eggerthellales','Eggerthellaceae','Eggerthella','Eggerthella lenta'),
	 (577,'658082','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae',NULL,'Lachnospiraceae bacterium 2_1_58FAA'),
	 (578,'387090','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Phocaeicola','Phocaeicola coprophilus'),
	 (579,'626933','Bacteroidota','Bacteroidia','Bacteroidales','Odoribacteraceae','Odoribacter','Odoribacter laneus'),
	 (580,'1681','Actinomycetota','Actinomycetes','Bifidobacteriales','Bifidobacteriaceae','Bifidobacterium','Bifidobacterium bifidum'),
	 (581,'658089','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae',NULL,'Lachnospiraceae bacterium 5_1_63FAA'),
	 (582,'39496','Bacillota','Clostridia','Eubacteriales','Eubacteriaceae','Eubacterium','Eubacterium ventriosum'),
	 (583,NULL,'Bacillota','Erysipelotrichia','Erysipelotrichales','Coprobacillaceae','Coprobacillus','Coprobacillus_sp_29_1');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (584,'1264','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Ruminococcus','Ruminococcus albus'),
	 (585,'457412','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Ruminococcus','Ruminococcus sp. 5_1_39BFAA'),
	 (586,'1736','Bacillota','Clostridia','Eubacteriales','Eubacteriaceae','Eubacterium','Eubacterium limosum'),
	 (587,'338188','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides finegoldii'),
	 (588,'291645','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides nordii'),
	 (589,'104264','Bacteroidota','Flavobacteriia','Flavobacteriales','Flavobacteriaceae','Cellulophaga',NULL),
	 (590,'230143','Actinomycetota','Actinomycetes','Bifidobacteriales','Bifidobacteriaceae','Scardovia','Scardovia wiggsiae'),
	 (591,'1597','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Lacticaseibacillus','Lacticaseibacillus paracasei'),
	 (592,'469588','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides sp. 2_1_22'),
	 (594,'35833','Thermodesulfobacteriota','Desulfovibrionia','Desulfovibrionaceae','Desulfovibrionaceae','Bilophila','Bilophila wadsworthia');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (595,'46506','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides stercoris'),
	 (596,'876','Thermodesulfobacteriota','Desulfovibrionia','Desulfovibrionales','Desulfovibrionaceae','Desulfovibrio','Desulfovibrio desulfuricans'),
	 (597,'214851','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Subdoligranulum','Subdoligranulum variabile'),
	 (598,'674529','Bacteroidota','Bacteroidia','Bacteroidales','Bacteroidaceae','Bacteroides','Bacteroides faecis'),
	 (599,'1358','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Lactococcus','Lactococcus lactis'),
	 (600,'39777','Bacillota','Negativicutes','Veillonellales','Veillonellaceae','Veillonella','Veillonella atypica'),
	 (601,'1305','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus sanguinis'),
	 (602,'847','Pseudomonadota','Betaproteobacteria','Burkholderiales','Oxalobacteraceae','Oxalobacter','Oxalobacter formigenes'),
	 (603,'46124','Bacillota','Bacilli','Lactobacillales','Carnobacteriaceae','Granulicatella','Granulicatella adiacens'),
	 (604,'187327','Bacillota','Negativicutes','Acidaminococcales','Acidaminococcaceae','Acidaminococcus','Acidaminococcus intestini');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (605,'154288','Bacillota','Erysipelotrichia','Erysipelotrichales','Turicibacteraceae','Turicibacter','Turicibacter sanguinis'),
	 (606,'28026','Actinomycetota','Actinomycetes','Bifidobacteriales','Bifidobacteriaceae','Bifidobacterium','Bifidobacterium pseudocatenulatum'),
	 (607,'84567','Bacteroidota','Sphingobacteriia','Sphingobacteriales','Sphingobacteriaceae','Pedobacter',NULL),
	 (608,'2710826','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Coprococcus','Coprococcus sp. ART55_1'),
	 (609,'131111','Actinomycetota','Actinomycetes','Actinomycetales','Actinomycetaceae','Schaalia','Schaalia turicensis'),
	 (610,'1257','Bacillota','Clostridia','Eubacteriales','Peptostreptococcaceae','Peptostreptococcus',NULL),
	 (611,'905','Bacillota','Negativicutes','Acidaminococcales','Acidaminococcaceae','Acidaminococcus','Acidaminococcus fermentans'),
	 (612,'76860','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus constellatus'),
	 (613,'56774','Bacillota','Clostridia','Eubacteriales','Eubacteriales Family XIII. Incertae Sedis',NULL,'[Eubacterium] infirmum'),
	 (614,'571','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Klebsiella','Klebsiella oxytoca');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (615,'36834','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Clostridium','Clostridium celatum'),
	 (616,'1624','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Ligilactobacillus','Ligilactobacillus salivarius'),
	 (617,'1302','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus gordonii'),
	 (618,'2860053','Bacillota','Clostridia','Eubacteriales','Clostridiaceae','Clostridium','Clostridium sp. L2_50'),
	 (619,'713','Pseudomonadota','Gammaproteobacteria','Pasteurellales','Pasteurellaceae','Actinobacillus',NULL),
	 (620,'1660','Actinomycetota','Actinomycetes','Actinomycetales','Actinomycetaceae','Schaalia','Schaalia odontolytica'),
	 (621,'53335','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Erwiniaceae','Pantoea',NULL),
	 (622,'39488','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae','Anaerobutyricum','Anaerobutyricum hallii'),
	 (623,'137732','Bacillota','Bacilli','Lactobacillales','Carnobacteriaceae','Granulicatella','Granulicatella elegans'),
	 (624,'726','Pseudomonadota','Gammaproteobacteria','Pasteurellales','Pasteurellaceae','Haemophilus','Haemophilus haemolyticus');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (625,'1078480','Pseudomonadota','Gammaproteobacteria','Pasteurellales','Pasteurellaceae','Haemophilus','Haemophilus sputorum'),
	 (626,'51123','Bacillota','Clostridia','Eubacteriales','Eubacteriales Family XIII. Incertae Sedis',NULL,'[Eubacterium] saphenum'),
	 (627,'447456','Candidatus Saccharibacteria',NULL,NULL,NULL,NULL,'candidate division TM7 single-cell isolate TM7c'),
	 (628,'37734','Bacillota','Bacilli','Lactobacillales','Enterococcaceae','Enterococcus','Enterococcus casseliflavus'),
	 (629,'487173','Bacillota','Negativicutes','Veillonellales','Veillonellaceae','Dialister','Dialister succinatiphilus'),
	 (630,'665951','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae',NULL,'Lachnospiraceae bacterium 8_1_57FAA'),
	 (631,'39491','Bacillota','Clostridia','Eubacteriales','Lachnospiraceae',NULL,'[Eubacterium] rectale'),
	 (632,'28141','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Cronobacter','Cronobacter sakazakii'),
	 (633,'447455','Candidatus Saccharibacteria',NULL,NULL,NULL,NULL,'candidate division TM7 single-cell isolate TM7b
'),
	 (634,'548','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Klebsiella','Klebsiella aerogenes');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (635,'461393','Actinomycetota','Actinomycetes','Actinomycetales','Actinomycetaceae','Actinomyces','Actinomyces massiliensis'),
	 (636,'52226','Bacillota','Negativicutes','Selenomonadales','Selenomonadaceae','Mitsuokella','Mitsuokella multacida'),
	 (637,'1095771','Bacillota','Clostridia','Eubacteriales','Oscillospiraceae','Ruminococcus','Ruminococcus sp. JC304'),
	 (638,'133926','Actinomycetota','Coriobacteriia','Coriobacteriales','Atopobiaceae','Olsenella','Olsenella uli'),
	 (639,'907','Bacillota','Negativicutes','Veillonellales','Veillonellaceae','Megasphaera','Megasphaera elsdenii'),
	 (640,'1750','Actinomycetota','Actinomycetes','Propionibacteriales','Propionibacteriaceae','Arachnia','Arachnia propionica'),
	 (641,'573','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Klebsiella','Klebsiella pneumoniae'),
	 (642,'28126','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Prevotella','Prevotella buccae'),
	 (643,'1243','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Leuconostoc',NULL),
	 (644,'2745','Pseudomonadota','Gammaproteobacteria','Oceanospirillales','Halomonadaceae','Halomonas',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (645,'244366','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Klebsiella','Klebsiella variicola'),
	 (646,'1246','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Leuconostoc','Leuconostoc lactis'),
	 (647,'33964','Bacillota','Bacilli','Lactobacillales','Lactobacillaceae','Leuconostoc','Leuconostoc citreum'),
	 (648,'416586','Bacillota','Negativicutes','Selenomonadales','Selenomonadaceae','Selenomonas','Selenomonas bovis'),
	 (649,'564','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Escherichia','Escherichia fergusonii'),
	 (650,'310514','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Hallella','Hallella multisaccharivorax'),
	 (651,'52584','Spirochaetota','Spirochaetia','Brachyspirales','Brachyspiraceae','Brachyspira','Brachyspira pilosicoli'),
	 (652,'48736','Pseudomonadota','Betaproteobacteria','Burkholderiales','Burkholderiaceae','Ralstonia',NULL),
	 (653,'9','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Erwiniaceae','Buchnera','Buchnera aphidicola'),
	 (654,'749535','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Klebsiella','Klebsiella sp. MS 92-3');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (655,'188913','Fusobacteriota','Fusobacteriia','Fusobacteriales','Fusobacteriaceae','Cetobacterium','Cetobacterium somerae'),
	 (656,'40214','Pseudomonadota','Gammaproteobacteria','Moraxellales','Moraxellaceae','Acinetobacter','Acinetobacter johnsonii'),
	 (657,'703','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Plesiomonas','Plesiomonas shigelloides'),
	 (658,'225324','Pseudomonadota','Alphaproteobacteria','Hyphomicrobiales',NULL,'Enhydrobacter','Enhydrobacter aerosaccus'),
	 (659,'642','Pseudomonadota','Gammaproteobacteria','Aeromonadales','Aeromonadaceae','Aeromonas',NULL),
	 (660,'61645','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Enterobacter','Enterobacter asburiae'),
	 (661,'539813','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Enterobacter','Enterobacter mori'),
	 (662,'181487','Actinomycetota','Actinomycetes','Actinomycetales','Actinomycetaceae','Schaalia','Schaalia cardiffensis'),
	 (663,'158836','Pseudomonadota','Gammaproteobacteria','Enterobacterales','Enterobacteriaceae','Enterobacter','Enterobacter hormaechei'),
	 (664,'399320','Spirochaetota','Spirochaetia','Spirochaetales','Sphaerochaetaceae','Sphaerochaeta',NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (665,'644','Pseudomonadota','Gammaproteobacteria','Aeromonadales','Aeromonadaceae','Aeromonas','Aeromonas hydrophila'),
	 (666,'28196','Campylobacterota','Epsilonproteobacteria','Campylobacterales','Arcobacteraceae','Arcobacter',NULL),
	 (667,'215','Campylobacterota','Epsilonproteobacteria','Campylobacterales','Helicobacteraceae','Helicobacter','Helicobacter fennelliae'),
	 (668,'33926','Mycoplasmatota','Mollicutes','Acholeplasmatales','Acholeplasmataceae','Candidatus Phytoplasma',NULL),
	 (669,'735','Pseudomonadota','Gammaproteobacteria','Pasteurellales','Pasteurellaceae','Haemophilus','Haemophilus parahaemolyticus'),
	 (670,'665874','Pseudomonadota','Burkholderiales','Comamonadaceae',NULL,'Limnohabitans',NULL),
	 (671,'246144','Bacillota','Bacilli','Lactobacillales','Enterococcaceae','Enterococcus','Enterococcus italicus'),
	 (672,'213119','Thermodesulfobacteriota','Desulfobacteria','Desulfobacterales','Desulfobacteraceae',NULL,NULL),
	 (673,'95818','Candidatus Saccharibacteria',NULL,NULL,NULL,NULL,NULL),
	 (674,'1090','Chlorobiota',NULL,NULL,NULL,NULL,NULL);
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (675,'32061','Chloroflexota','Chloroflexia',NULL,NULL,NULL,NULL),
	 (676,'203490','Fusobacteriota','Fusobacteriia',NULL,NULL,NULL,NULL),
	 (677,'203691','Spirochaetota',NULL,NULL,NULL,NULL,NULL),
	 (678,'508458','Synergistota',NULL,NULL,NULL,NULL,NULL),
	 (679,'7711','Chordata',NULL,NULL,NULL,NULL,NULL),
	 (680,'28890','Euryarchaeota',NULL,NULL,NULL,NULL,NULL),
	 (681,'2045302','Pseudomonadota','Betaproteobacteria','Burkholderiales','Comamonadaceae','Ottowia','Ottowia massiliensis'),
	 (682,'272548','Actinomycetota','Actinomycetes','Actinomycetales','Actinomycetaceae','Actinomyces','Actinomyces dentalis'),
	 (683,'28132','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Prevotella','Prevotella melaninogenica'),
	 (684,'1739423','Actinomycetota','Actinomycetes','Micrococcales','Micrococcaceae','Rothia','Rothia sp. HMSC068E02');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (685,'712124','Actinomycetota','Actinomycetes','Actinomycetales','Actinomycetaceae','Actinomyces','Actinomyces sp. oral taxon 448'),
	 (686,'1656','Actinomycetota','Actinomycetes','Actinomycetales','Actinomycetaceae','Actinomyces','Actinomyces viscosus'),
	 (687,'470565','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Prevotella','Prevotella histicola'),
	 (688,'712438','Bacteroidota','Bacteroidia','Bacteroidales','Porphyromonadaceae','Porphyromonas','Porphyromonas sp. oral taxon 279'),
	 (689,'1739254','Pseudomonadota','Gammaproteobacteria','Pasteurellales','Pasteurellaceae','Haemophilus','Haemophilus sp. HMSC066D02'),
	 (690,'486','Pseudomonadota','Betaproteobacteria','Neisseriales','Neisseriaceae','Neisseria','Neisseria lactamica'),
	 (691,'1911679','Bacillota','Negativicutes','Veillonellales','Veillonellaceae','Veillonella','Veillonella infantium'),
	 (692,'712888','Actinomycetota','Actinomycetes','Actinomycetales','Actinomycetaceae','Actinobaculum','Actinobaculum sp. oral taxon 183'),
	 (693,'563031','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Prevotella','Prevotella sp. C561'),
	 (694,'936548','Actinomycetota','Actinomycetes','Actinomycetales','Actinomycetaceae','Actinomyces','Actinomyces sp. ICM47');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (695,'1581132','Actinomycetota','Actinomycetes','Micrococcales','Micrococcaceae','Rothia','Rothia sp. HMSC08A08'),
	 (696,'135083','Bacillota','Negativicutes','Selenomonadales','Selenomonadaceae','Selenomonas','Selenomonas noxia'),
	 (697,'68892','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus infantis'),
	 (698,'556499','Actinomycetota','Actinomycetes','Propionibacteriales','Propionibacteriaceae','Propionibacterium','Propionibacterium acidifaciens'),
	 (699,'28037','Bacillota','Bacilli','Lactobacillales','Streptococcaceae','Streptococcus','Streptococcus mitis'),
	 (700,'60133','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Prevotella','Prevotella pallens'),
	 (701,'712710','Bacteroidota','Bacteroidia','Bacteroidales','Tannerellaceae','Tannerella','Tannerella serpentiformis'),
	 (702,'28112','Bacteroidota','Bacteroidia','Bacteroidales','Tannerellaceae','Tannerella','Tannerella forsythia'),
	 (703,'1019','Bacteroidota','Flavobacteriia','Flavobacteriales','Flavobacteriaceae','Capnocytophaga','Capnocytophaga sputigena'),
	 (704,'76857','Fusobacteriota','Fusobacteriia','Fusobacteriales','Fusobacteriaceae','Fusobacterium','Fusobacterium polymorphum');
INSERT INTO microbiome.microbe (microbe_id,ncbi_id,phylum,class,`order`,family,genus,species) VALUES
	 (705,'860','Fusobacteriota','Fusobacteriia','Fusobacteriales','Fusobacteriaceae','Fusobacterium','Fusobacterium periodonticum'),
	 (706,'340486','Bacteroidota','Bacteroidia','Bacteroidales','Prevotellaceae','Prevotella','Prevotella conceptionensis'),
	 (707,'653385','Actinomycetota','Actinomycetes','Actinomycetales','Actinomycetaceae','Actinomyces','Actinomyces sp. oral taxon 849'),
	 (708,'423477','Bacillota','Negativicutes','Veillonellales','Veillonellaceae','Veillonella','Veillonella rogosae'),
	 (709,'1986146','Thermodesulfobacteriota','Desulfobulbia','Desulfobulbales','Desulfobulbaceae','Desulfobulbus','Desulfobulbus oralis'),
	 (710,'327575','Bacteroidota','Flavobacteriia','Flavobacteriales','Flavobacteriaceae','Capnocytophaga','Capnocytophaga leadbetteri');
